.PHONY: setup build run-dist test report check clean

setup:
	.\gradlew.bat clean install

build:
	.\gradlew.bat clean build

run-dist:
	.\gradlew.bat run

test:
	.\gradlew.bat test

report:
	.\gradlew.bat jacocoTestReport

check:
	.\gradlew.bat check

clean:
	.\gradlew.bat clean