.PHONY: build run test report check clean

build:
	cd app && ./gradlew clean build

run:
	cd app && ./gradlew run

test:
	cd app && ./gradlew test

report:
	cd app && ./gradlew jacocoTestReport

check:
	cd app && ./gradlew check

clean:
	cd app && ./gradlew clean